### ISSUE TITLE
Add settings for default model to rmplan project config

### ISSUE THREAD

**Issue by dimfeld** [dimfeld/llmutils#34]
Add to rmplan project config:
 
```yaml
models:
  execution: "modelSpec for rmplan run model"
  convert_yaml: "modelSpec for rmplan markdown-to-yaml extraction"
```
